#+STARTUP: showall
#+STARTUP: lognotestate
#+TAGS:
#+SEQ_TODO: TODO STARTED DONE DEFERRED CANCELLED | WAITING DELEGATED APPT
#+DRAWERS: HIDDEN STATE
#+TITLE: MSR course
#+CATEGORY: 
#+PROPERTY: header-args:sql             :engine postgresql  :exports both :cmdline csc370
#+PROPERTY: header-args:sqlite          :db /path/to/db  :colnames yes
#+PROPERTY: header-args:C++             :results output :flags -std=c++14 -Wall --pedantic -Werror
#+PROPERTY: header-args:R               :results output  :colnames yes
#+OPTIONS: ^:nil


* :TOC:
- [[#students][Students]]
- [[#schedule][Schedule]]
- [[#schedule-1][Schedule]]
- [[#by-week][By week]]
- [[#reading-material-outdated][Reading Material (outdated)]]
  - [[#week-1][Week 1]]
  - [[#week-2][Week 2]]
  - [[#week-3-predicting-bugs][Week 3: Predicting Bugs]]
  - [[#week-4-mining-social-structures-and-code-reviews][Week 4: Mining Social Structures and Code Reviews]]
  - [[#week-5][Week 5]]
  - [[#week-6-mining-unstructured-data][Week 6: Mining Unstructured Data]]
  - [[#week-7][Week 7]]
  - [[#week-8][Week 8]]
  - [[#week-9-mining-mobile-apps][Week 9: Mining Mobile Apps]]
  - [[#week-10-large-scale-analysis-i][Week 10: Large-Scale Analysis I]]
  - [[#week-11-large-scale-analysis-ii][Week 11: Large-Scale Analysis II]]

* Students                                                            :crypt:
-----BEGIN PGP MESSAGE-----

hQEMA7UCIcJGxmcFAQgAk8Z9uExy8LkLBT6Ox2kUxhU55PrEsshqpR9W3fnaHP/x
6OfN+Ks6GZbFW3GsnwJaZJVKyBEDpk+zz2o1R1G5NaEJ4JYn3T5+Z3SUNu/r2FBK
SZEyCzHNX4S/hrf+lm3j34DbU0S3eYY/zQErKulw+qQrzyvP5UdmPIpfmjtHP8Uy
odO5xqI4EyvAeCQVcm8DkoXo9u3HsOMLpOynVRJvZjDZS3QcJlQjsssgxJgmP3NT
GnwC3GB/SwH0Q9CbE2zjvEbzxzgD/pJg9Cob3EzCC4Kd0j02FzKbDz8xcsfIw4Ai
GpYSCFCBI8RfuQO4/azvanXNzyRAm5LgGjqzGkRmbNLA0QFQbNCu7Yrhcl7Ye8WZ
gVQCheQmgN6PfyXWGXbPYGeJmhf1sgEamPz2pULk9xTqxJbJCDtYbxocAegCQ/Zv
UojO50whBO78i0q1fnNFtCGWJqjNXLYM11vcAcoZIJeHN2SP4QuFEi1qpUJhabiY
RiJCET17uTYlLmmZQA32X5qIwZPqCBysLuVaB1+WYyEzTIBE8TRhRHcHQ8iVc604
ZsIQETVFGG1DfPi75uxBMPobsaisPMEM8GAUMxGhwGSOXRKXaY1jc4+IkXmM7awa
8nEkA5AMo1kUk5csQAY+n4mow0xQ3q3U9m0VJi2Epu763qf21Fq7PM1B2qEw+dlJ
CY5jG1es8dWQeopa46S5JuRNGcTQxwhL8DqXmNSUYeGRL1Yqxdoblx3zBnodVECa
78Uh0KVQXmtbAdVYHVfrBUGFc6i49I8lU2JmUd+F5iK4TsHIhsLJdUEmnVjoHSvJ
vrlFJI0Rse4CbuGCnIARK1MBWckFaxATlPWyIHwaeM+/3qGTZujoAujjEw82dGZA
sMsu
=47qb
-----END PGP MESSAGE-----

* Schedule 

#+BEGIN_EXAMPLE
September 2017      

Su Mo Tu We Th Fr Sa    
                8     MSR Intro
      12       15     MSR Tutorial
      19       22     MSR tutorial/Papers 1
      26       29     Papers 2/Papers 3

October 2017       
Su Mo Tu We Th Fr Sa   
       3        6     Papers 4/Papers 5
      10       13     Assignment #1 results
      17       20     papers 6/papers 7
      24       27     Proposal presentations
      31        3     papers 8/papers 9
                            
November 2017        
       7       10     papers 10/papers 11
      14       17     Reading break (I am away)
      21       24     Assignment #2 results/papers 12
      28        1     Project Presentations
#+END_EXAMPLE

- Only one critique presentation per week.
- At most two papers are marked for critique each week. 1/2 the class will be assigned to each

* Schedule

| 1. Bug prediction                      | <2017-09-22 Fri> |
| 2. Bug prediction                      | <2017-09-26 Tue> |
| 3. Code reviews                        | <2017-09-29 Fri> |
| 4. Social structures                   | <2017-10-03 Tue> |
| 5. Unstructured data                   | <2017-10-06 Fri> |
| 6. Large scala analysis                | <2017-10-17 Tue> |
| 7. Mining version control              | <2017-10-20 Fri> |
| 8. Co-chance                           | <2017-10-31 Tue> |
| 9. CI and Energy                       | <2017-11-03 Fri> |
| 10. Monitoring developers              | <2017-11-07 Tue> |
| 11. Programming languages and language | <2017-11-10 Fri> |
| 12. Licensing and Provenance           | <2017-11-24 Fri> |

* By week

1. Bug prediction 1

2. Bug prediction 2

3. Code reviews <2017-09-29 Fri>

An Empirical Study of the Impact of Modern Code Review Practices on Software Quality 
Shane McIntosh, Yasutaka Kamei, Bram Adams, and Ahmed E. Hassan 

(critique/presentation) Investigating technical and non-technical factors influencing modern code review
Olga Baysal, Oleksii Kononenko, Reid Holmes and Michael W. Godfrey

4. Social structures <2017-10-03 Tue>

On the Role of Developer's Scattered Changes in Bug Prediction 
Dario Di Nucci, Fabio Palomba, Sandro Siravo, Gabriele Bavota, Rocco Oliveto, and Andrea De Lucia

(critique/presentation) Does Distributed Development Affect Software Quality? An Empirical Case Study of Windows Vista 
Christian Bird, Nachiappan Nagappan, Premkumar Devanbu, Harald Gall, and Brendan Murphy

5. Unstructured data + <2017-10-06 Fri>

(critique/presentation) Listening to programmers Taxonomies and characteristics of comments in operating system code 
Yoann Padioleau, Lin Tan, Yuanyuan Zhou

Identifying reasons for software change using historic databases. 
Audris Mockus and Larry G. Votta

6. Large scala analysis <2017-10-17 Tue>

Scalable statistical bug isolation 
Ben Liblit, Mayur Naik, Alice X. Zheng, Alex Aiken, and Michael I. Jordan

(critique/presentation) Towards Building a Universal Defect Prediction Model 
Feng Zhang, Audris Mockus, Iman Keivanloo, Ying Zou: Towards building a universal defect prediction model.

7. Mining version control  <2017-10-20 Fri>

(critique/presentation) Amassing and indexing a large sample of version control systems: towards the census of public source code history 
Audris Mockus

The Promises and Perils of Mining Github 
Eirini Kalliamvakou, Georgios Gousios, Kelly Blincoe, Leif Singer, Daniel M. German, Daniela Damian

8. Co-chance <2017-10-31 Tue>

(critique/presentation) Developer-related factors in change prediction: an empirical assessment
Gemma Catolino, Fabio Palomba, Andrea De Lucia, Filomena Ferrucci, Andy

Automatic classication of large changes into maintenance categories.
Hindle A, German D, Godfrey M, Holt R (2009)  
Program comprehension, 2009. ICPC ’09. 17th International Conference on IEEE, pp. 30–39

9. CI and Energy  <2017-11-03 Fri>

(critique/presentation) Oops, my tests broke the build: an explorative analysis of Travis CI with GitHub
Beller, Moritz & Gousios, Georgios & Zaidman, And

Green mining: a methodology of relating software change and configuration to power consumption
Abram Hindle

10. Monitoring developers  <2017-11-07 Tue>

(critique/presentation) When, how, and why developers (do not) test in their IDEs
Moritz Beller, Georgios Gousios, Annibale Panichella, Andy Zaidman

An empirical study of the effect of file editing patterns on software quality
Feng Zhang, Foutse Khomh, Ying Zou, Ahmed E. Hassan:

11. Programming languages and language  <2017-11-10 Fri>

On the naturalness of software
A. Hindle, E. T. Barr, Z. Su, M. Gabel, and P. Devanbu

(critique/presentation) Mining billions of AST nodes to study actual and potential usage of Java language features.
Robert Dyer, Hridesh Rajan, Hoan Anh Nguyen, Tien N. Nguyen:

12. Licensing and Provenance <2017-11-24 Fri>

Christopher Vendome, Gabriele Bavota, Massimiliano Di Penta, Mario Linares Vásquez, Daniel M. Germán, Denys Poshyvanyk:
License usage and changes: a large-scale study on gitHub. Empirical Software Engineering 22(3): 1537-1577 (2017)

Julius Davies, Daniel M. Germán, Michael W. Godfrey, Abram Hindle:
Software Bertillonage - Determining the provenance of software development artifacts. Empirical Software Engineering 18(6): 1195-1237 (2013)






* Reading Material (outdated)
** Week 1
- *The Road Ahead for Mining Software Repositories* by Ahmed E. Hassan
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/presentations/MSRTheRoadAhead_ICSM2008_Ahmed_Hassan.pdf][Link]]
** Week 2
- *Future of Mining Software Archives: A Roundtable* by Michael W. Godfrey
  @@html:<br>@@
  [[http://plg2.cs.uwaterloo.ca/~migod/papers/2009/IEEE-Software-MSR-rountable.pdf][Link]]
** Week 3: Predicting Bugs
- *Predicting fault incidence using software change history* by Todd L. Graves, Alan F. Karr, J. S. Marron, and Harvey P. Siy
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/FaultIncidence_TSE2000.pdf][Link]]
  @@html:<br>@@
  *Analysis Techniques:* Basic linear regression, GLM, R2, model error, exponential decay
- *Predictors of customer perceived software quality* by Audris Mockus, Ping Zhang, and Paul Luo Li
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/PerceivedQuality_ICSE2005.pdf][Link]]
  @@html:<br>@@
  *Analysis Techniques:* Classification, Logistic Regression (Building and Interpreting Co-efficients), R2, model error
- *Predicting Defects for Eclipse* by Thomas Zimmermann, Rahul Premraj, and Andreas Zeller
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/promise2007-dataset-20a.pdf][Link]]
  @@html:<br>@@
  *Analysis Techniques:* Using R, Classification, Ranking
- *How, and Why, Process Metrics are better* by Foyzur Rahman and Premkumar Devanbu
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/HowAndWhyProcessMetricsAreBetter.pdf][Link]]
  @@html:<br>@@
- *Predicting Bugs from History* by Thomas Zimmermann, Nachiappan Nagappan, and Andreas Zeller
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/PredictingBugs_EvolutionBook.pdf][Link]]
  @@html:<br>@@
** Week 4: Mining Social Structures and Code Reviews
- *Will My Patch Make it? and How Fast?: Case Study on the Linux Kernel* by Yujuan Jiang, Bram Adams, Daniel M. German
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/LinuxPatch_MSR2013.pdf][Link]]
  @@html:<br>@@
  *Analysis Techniques:* Decision Tree
- *On the Role of Developer's Scattered Changes in Bug Prediction* by Dario Di Nucci, Fabio Palomba, Sandro Siravo, Gabriele Bavota, Rocco Oliveto, and Andrea De Lucia
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/OnTheRoleOfDeveloperScatteredChangesIn%20BugPrediction.pdf][Link]]
  @@html:<br>@@
- *An Empirical Study of the Impact of Modern Code Review Practices on Software Quality* by Shane McIntosh, Yasutaka Kamei, Bram Adams, and Ahmed E. Hassan
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/AnEmpiricalStudyOfTheImpactOfModern%20CodeReviewPracticesOnSoftwareQuality.pdf][Link]]
  @@html:<br>@@
  *Analysis Techniques:* Bootstrap validation
- *Does Distributed Development Affect Software Quality? An Empirical Case Study of Windows Vista* by Christian Bird, Nachiappan Nagappan, Premkumar Devanbu, Harald Gall, and Brendan Murphy
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/DistributedDevelopment_CACM2009.pdf][Link]]
  @@html:<br>@@
** Week 5
** Week 6: Mining Unstructured Data
- *Creating and Evolving Developer Documentation: Understanding the Decisions of Open Source Contributors* by Barthelemy Dagenais and Martin P. Robillard
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/Documentation_FSE2010.pdf][Link]]
  @@html:<br>@@
  *Analysis Techniques:* Grounded Theory
- *Semantic clustering: Identifying topics in source code* by Adrian Kuhn, Stephane Ducasse, and Tudor Girba
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/SemanticClustering_IST2007.pdf][Link]]
  @@html:<br>@@
  *Analysis Techniques:* LDA, LSI
- *Listening to programmers Taxonomies and characteristics of comments in operating system code* by Yoann Padioleau, Lin Tan, Yuanyuan Zhou
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/Comments_ICSE2009.pdf][Link]]
  @@html:<br>@@
- *Identifying reasons for software change using historic databases* by Audris Mockus and Larry G. Votta
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/ReasonforChange_ICSM2000.pdf][Link]]
  @@html:<br>@@
** Week 7
** Week 8
** Week 9: Mining Mobile Apps
- *A Measurement Study of Google Play* by Nicolas Viennot, Edward Garcia, Jason Nieh
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/GooglePlay_METRICS2014.pdf][Link]]
  @@html:<br>@@
- *API Change and Fault Proneness: a Threat to the Success of Android Apps* by Mario Linares Vasquez, Gabriele Bavota, Carlos Bernal-Cardenas, Massimiliano Di Penta, Rocco Oliveto, Denys Poshyvanyk
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/APIApps_FSE2013.pdf][Link]]
  @@html:<br>@@
- *Software Analytics for Mobile Applications - Insights & Lessons Learned* by Roberto Minelli, Michele Lanza
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/MobileAnalytics_CMSR2013.pdf][Link]]
  @@html:<br>@@
- *Visual Analytics in Software Maintenance: Challenges and Opportunities* by Alex Telea and and Ozan Ersoy and Lucian Voinea
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/VisualAnalystics%20_EuroVAST2010.pdf][Link]]
  @@html:<br>@@
** Week 10: Large-Scale Analysis I
- *Improving Software Diagnosability via Log Enhancement* by Ding Yuan, Jing Zheng, Soyeon Park, Yuanyuan Zhou, and Stefan Savage
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/LogEnhancer_ASPLOS2011.pdf][Link]]
  @@html:<br>@@
- *The Promises and Perils of Mining Github* by Eirini Kalliamvakou, Georgios Gousios, Kelly Blincoe, Leif Singer, Daniel M. German, Daniela Damian
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/MiningGitHub_MSR2014.pdf][Link]]
  @@html:<br>@@
- *Towards Building a Universal Defect Prediction Model* by Feng Zhang, Audris Mockus, Iman Keivanloo, Ying Zou
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/UniversalModel_MSR2014.pdf][Link]]
  @@html:<br>@@
- *Bugs as deviant behavior: A general approach to inferring errors in systems code* by Dawson Engler, David Yu Chen, Seth Hallem, Andy Chou, and Benjamin Chelf
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/BugsAsDeviantBehavior_SOSP2001.pdf][Link]]
  @@html:<br>@@
  *Analysis Techniques:* Markov Models
- *Scalable statistical bug isolation* by Ben Liblit, Mayur Naik, Alice X. Zheng, Alex Aiken, and Michael I. Jordan
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/ScalableBugs_PLDI2005.pdf][Link]]
  @@html:<br>@@
** Week 11: Large-Scale Analysis II
- *Capturing, indexing, clustering, and retrieving system history* by Ira Cohen, Steve Zhang, Moises Goldszmidt, Julie Symons, Terence Kelly, and Armando Fox
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/CapturingIndexing_SOSP2005.pdf][Link]]
  @@html:<br>@@
- *vPerfGuard: an Automated Model-Driven Framework for Application Performance Diagnosis in Consolidated Cloud Environment* by Pengcheng Xiong, Calton Pu, Xiaoyun Zhu, and Rean Griffith
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/VMWARE_ICPE2013.pdf][Link]]
  @@html:<br>@@
- *Performance Debugging in the Large via Mining Millions of Stack Traces* by Shi Han, Yingnong Dang, Song Ge, Dongmei Zhang, and Tao Xie
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/StackMine_ICSE2012.pdf][Link]]
  @@html:<br>@@
- *Amassing and indexing a large sample of version control systems: towards the census of public source code history* by Audris Mockus
  @@html:<br>@@
  [[http://research.cs.queensu.ca/~ahmed/home/teaching/CISC880/F16/papers/Amassing_MSR2009.pdf][Link]]
  @@html:<br>@@
